# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# # Default language
# en:
#   languageCode: en-us
#   # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
#   #contentDir: content/en

# # Uncomment the lines below to configure your website in a second language.
# # zh:
# #  languageCode: zh-Hans
# #  contentDir: content/zh
# #  title: Chinese website title...
# #  params:
# #    description: Site description in Chinese...
# #  menu:
# #    main:
# #      - name: 传
# #        url: '#about'
# #        weight: 1

en:
  locale: en-us
  weight: 1
  contentDir: content/en
  title: "Academic Page"
  params:
    description: "Personal academic website"

zh:
  locale: zh-Hans
  weight: 2
  contentDir: content/zh
  title: "学术主页"
  params:
    description: "个人学术主页"